### ISSUE TITLE
undefined method helper_method for ActionController::API:Class

### ISSUE THREAD

**Issue by hoahm** [plataformatec/has_scope#83]
Does current version of has_scope gem support Rails 5? I got this error when trying to use has_scope with ActionController::API

    /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/has_scope-0.6.0/lib/has_scope.rb:204:in `block in <top (required)>': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:44:in `each'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta1/lib/action_controller/api.rb:144:in `<class:API>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta1/lib/action_controller/api.rb:87:in `<module:ActionController>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0.beta1/lib/action_controller/api.rb:5:in `<top (required)>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:302:in `require'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:302:in `block in require'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:266:in `block in load_dependency'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:682:in `new_constants_in'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:266:in `load_dependency'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:302:in `require'
    from /Users/hoanghoa/projects/abc-ror/app/controllers/api/v1/application_controller.rb:1:in `<top (required)>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:492:in `load'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:492:in `block in load_file'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:682:in `new_constants_in'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:491:in `load_file'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:388:in `block in require_or_load'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/concurrency/share_lock.rb:115:in `exclusive'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies/interlock.rb:11:in `loading'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:37:in `load_interlock'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:369:in `require_or_load'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:345:in `depend_on'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.beta1/lib/active_support/dependencies.rb:261:in `require_dependency'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/engine.rb:475:in `each'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/engine.rb:475:in `block in eager_load!'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/engine.rb:473:in `each'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/engine.rb:473:in `eager_load!'
    from /Users/hoanghoa/projects/abc-ror/config.ru:6:in `block in <main>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
    from /Users/hoanghoa/projects/abc-ror/config.ru:in `new'
    from /Users/hoanghoa/projects/abc-ror/config.ru:in `<main>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/server.rb:56:in `app'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/server.rb:134:in `log_to_stdout'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/server.rb:74:in `start'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:85:in `tap'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:85:in `server'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/command.rb:20:in `run'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.beta1/lib/rails/commands.rb:19:in `<top (required)>'
    from /Users/hoanghoa/projects/abc-ror/bin/rails:9:in `require'
    from /Users/hoanghoa/projects/abc-ror/bin/rails:9:in `<top (required)>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.1/lib/spring/client/rails.rb:28:in `load'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.1/lib/spring/client/rails.rb:28:in `call'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.1/lib/spring/client/command.rb:7:in `call'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.1/lib/spring/client.rb:28:in `run'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.1/bin/spring:51:in `<top (required)>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.1/lib/spring/binstub.rb:11:in `load'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.6.1/lib/spring/binstub.rb:11:in `<top (required)>'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/hoanghoa/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/hoanghoa/projects/abc-ror/bin/spring:13:in `<top (required)>'
    from bin/rails:3:in `load'
    from bin/rails:3:in `<main>'

**Comment by hoahm** [comment]
It already fixed on https://github.com/plataformatec/has_scope/pull/79
